steps:
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}","."]

  - id: "docker-push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]

  - id: "migration"
    name: "${_IMAGE_NAME}"
    env:
      - "DATABASE_NAME=abhishek"
      - "DATABASE_USER=root"
      - "DATABASE_HOST=11.116.137.2"
      - "DATABASE_TYPE=${_DATABASE_TYPE}"
      - "DATABASE_PASS=abhishek"
    entrypoint: python   # for example
    args: ["migrate.py"] # for example

options:
  pool:
    name: projects/sqll-366913/locations/asia-southeast1/workerPools/worker-pool
  dynamic_substitutions: true
options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DATABASE_TYPE: postgres
  _IMAGE_NAME: gcr.io/sqll-366913/sample-private-pool

# [END cloudbuild_sql_private_pool]
